/* Generated By:JavaCC: Do not edit this line. Parser.java */
package gzotpa.parser;
import gzotpa.ast.*;
import gzotpa.entity.*;
import gzotpa.type.*;
import gzotpa.exception.*;
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;


public class Parser implements ParserConstants {
        private String sourceName;
        private boolean mainFunc;
        public Parser(Reader s, String name) {
                this(s);
                this.sourceName = name;
                this.mainFunc = false;
        }
        public AST parse() throws SyntaxException {
        try {
            return compilation_unit();
        }
        catch (TokenMgrError err) {
            throw new SyntaxException(err.getMessage());
        }
        catch (ParseException ex) {
            throw new SyntaxException(ex.getMessage());
        }
        catch (LookaheadSuccess err) {
            throw new SyntaxException("syntax error");
        }
    }
        static public AST parseFile(File file)
                                                                throws SyntaxException, FileException {
                return newFileParser(file).parse();
        }
        static final public String SOURCE_ENCODING = "UTF-8";
        static public Parser newFileParser(File file)
                                                                                throws FileException {
                try {
                        BufferedReader r =
                                new BufferedReader(
                                        new InputStreamReader(new FileInputStream(file),
                                                SOURCE_ENCODING));
                        return new Parser(r, file.getPath());
                }
                catch (FileNotFoundException ex) {
                        throw new FileException(ex.getMessage());
                }
                catch (UnsupportedEncodingException ex) {
                        throw new Error("Gzotpa! UTF-8 is not supported??: " + ex.getMessage());
                }
        }
        protected Location location(Token t) {
        return new Location(sourceName, t);
    }
    private char unescapeOctal(String s) throws ParseException {
        int x = Integer.parseInt(s, 8);
        if (x > 255) throw new ParseException("Gzotpa! Octal ascii exceeds 255!");
        return (char)x;
    }
    private char unescapeSeq(char c) throws ParseException {
        switch (c) {
        case '"': return '"';
        case '\\': return '\\';
        case '\'': return '\'';
        case 'n': return '\n';
        default:
            throw new ParseException("Gzotpa! Unknown escape sequence: \"\\" + c + "!");
        }
    }
    private String stringValue(String _image) throws ParseException {
        int pos = 0;
        int idx;
        StringBuffer buf = new StringBuffer();
        String image = _image.substring(1, _image.length() - 1);

        while ((idx = image.indexOf("\\", pos)) >= 0) {
            buf.append(image.substring(pos, idx));
            if (image.length() >= idx + 4
                    && Character.isDigit(image.charAt(idx+1))
                    && Character.isDigit(image.charAt(idx+2))
                    && Character.isDigit(image.charAt(idx+3))) {
                buf.append(unescapeOctal(image.substring(idx+1, idx+4)));
                pos = idx + 4;
            }
            else {
                buf.append(unescapeSeq(image.charAt(idx+1)));
                pos = idx + 2;
            }
        }
        if (pos < image.length()) {
            buf.append(image.substring(pos, image.length()));
        }
        return buf.toString();
    }
    private long integerValue(String s) {
        if (s.startsWith("0x") || s.startsWith("0X")) {
            return Long.parseLong(s.substring(2), 16);
        }
        else if (s.startsWith("0") && !s.equals("0")) {
            return Long.parseLong(s.substring(1), 8);
        }
        else {
            return Long.parseLong(s, 10);
        }
    }
    private boolean isLetter(char c) {
        return (c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z');
    }

  final public Params params() throws ParseException {
    Token t = new Token();
    Params params;
    if (jj_2_1(2147483647)) {
            {if (true) return new Params(location(t), new ArrayList<Parameter>());}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case BOOL:
      case INT:
      case STR:
      case IDENTIFIER:
        params = fixedparams();
            {if (true) return params;}
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Params fixedparams() throws ParseException {
    List<Parameter> params = new ArrayList<Parameter>();
    Parameter param, param1;
    param1 = param();
                     params.add(param1);
    label_1:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_1;
      }
      jj_consume_token(27);
      param = param();
                                       params.add(param);
    }
            {if (true) return new Params(param1.location(), params);}
    throw new Error("Missing return statement in function");
  }

  final public Parameter param() throws ParseException {
    TypeNode t;
    String n;
    t = type();
    n = name();
                        {if (true) return new Parameter(t, n);}
    throw new Error("Missing return statement in function");
  }

  final public BlockNode block() throws ParseException {
    Token t;
    DefinedVariable var;
    List<DefinedVariable> vars = new ArrayList<DefinedVariable>();
    StmtNode stmt;
    List<StmtNode> stmts = new ArrayList<StmtNode>();
    List<Boolean> order = new ArrayList<Boolean>();
    t = jj_consume_token(28);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case NULL:
      case BOOL:
      case TRUE:
      case FALSE:
      case INT:
      case STR:
      case IF:
      case WHILE:
      case FOR:
      case RETURN:
      case BREAK:
      case CONTINUE:
      case NEW:
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 28:
      case 32:
      case 33:
      case 58:
      case 59:
      case 63:
      case 64:
      case 65:
      case 66:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      if (jj_2_3(2147483647)) {
        var = defvar();
                               if (var.hasInitializer()) {
                                ExprStmtNode tmp = new ExprStmtNode(new AssignNode(new VariableNode(var), var.initializer()));
                                var.deletInitializer();
                                vars.add(var); order.add(true);
                                stmts.add(tmp); order.add(false);
                            }
                            else {
                                vars.add(var); order.add(true);
                            }
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NULL:
        case TRUE:
        case FALSE:
        case IF:
        case WHILE:
        case FOR:
        case RETURN:
        case BREAK:
        case CONTINUE:
        case NEW:
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 28:
        case 32:
        case 33:
        case 58:
        case 59:
        case 63:
        case 64:
        case 65:
        case 66:
          stmt = stmt();
                               stmts.add(stmt); order.add(false);
          break;
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    jj_consume_token(29);
            {if (true) return new BlockNode(location(t), vars, stmts, order);}
    throw new Error("Missing return statement in function");
  }

  final public TypeNode type() throws ParseException {
  TypeRef ref;
    ref = typeref();
                    {if (true) return new TypeNode(ref);}
    throw new Error("Missing return statement in function");
  }

  final public TypeRef typeref() throws ParseException {
    TypeRef ref;
    Token t;
    ref = typeref_base();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      if (jj_2_4(2)) {
        jj_consume_token(30);
        jj_consume_token(31);
            ref = new ArrayTypeRef(ref);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 30:
          jj_consume_token(30);
          t = jj_consume_token(INTEGER);
          jj_consume_token(31);
            ref = new ArrayTypeRef(ref, integerValue(t.image));
          break;
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
            {if (true) return ref;}
    throw new Error("Missing return statement in function");
  }

  final public TypeNode newtype() throws ParseException {
  TypeRef newref;
    newref = newtyperef();
                          {if (true) return new TypeNode(newref);}
    throw new Error("Missing return statement in function");
  }

  final public TypeRef newtyperef() throws ParseException {
    TypeRef ref;
    ExprNode e;
    ref = typeref_base();
    label_4:
    while (true) {
      if (jj_2_5(2)) {
        ;
      } else {
        break label_4;
      }
      jj_consume_token(30);
      e = expr();
      jj_consume_token(31);
            ref = new ArrayTypeRef(ref, e);
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_5;
      }
      jj_consume_token(30);
      jj_consume_token(31);
            ref = new ArrayTypeRef(ref);
    }
            {if (true) return ref;}
    throw new Error("Missing return statement in function");
  }

  final public TypeRef typeref_base() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VOID:
      t = jj_consume_token(VOID);
                          {if (true) return new VoidTypeRef(location(t));}
      break;
    case BOOL:
      t = jj_consume_token(BOOL);
                          {if (true) return IntegerTypeRef.intRef(location(t), true);}
      break;
    case INT:
      t = jj_consume_token(INT);
                          {if (true) return IntegerTypeRef.intRef(location(t));}
      break;
    case STR:
      t = jj_consume_token(STR);
                          {if (true) return new StringTypeRef("string", location(t));}
      break;
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
                          {if (true) return new ClassTypeRef(location(t), t.image);}
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public List<StmtNode> stmts() throws ParseException {
    List<StmtNode> ss = new ArrayList<StmtNode>();
    StmtNode s;
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case IF:
      case WHILE:
      case FOR:
      case RETURN:
      case BREAK:
      case CONTINUE:
      case NEW:
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 28:
      case 32:
      case 33:
      case 58:
      case 59:
      case 63:
      case 64:
      case 65:
      case 66:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_6;
      }
      s = stmt();
                if (s != null) ss.add(s);
    }
            {if (true) return ss;}
    throw new Error("Missing return statement in function");
  }

  final public StmtNode stmt() throws ParseException {
    StmtNode n = null;
    ExprNode e = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 32:
      jj_consume_token(32);
      break;
    case NULL:
    case TRUE:
    case FALSE:
    case NEW:
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 33:
    case 58:
    case 59:
    case 63:
    case 64:
    case 65:
    case 66:
      e = expr();
      jj_consume_token(32);
                     n = new ExprStmtNode(e.location(), e);
      break;
    case 28:
      n = block();
      break;
    case IF:
      n = if_stmt();
      break;
    case WHILE:
      n = while_stmt();
      break;
    case FOR:
      n = for_stmt();
      break;
    case RETURN:
      n = return_stmt();
      break;
    case BREAK:
      n = break_stmt();
      break;
    case CONTINUE:
      n = continue_stmt();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
            {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public IfNode if_stmt() throws ParseException {
    Token t;
    ExprNode cond;
    StmtNode thenBody, elseBody = null;
    t = jj_consume_token(IF);
    jj_consume_token(33);
    cond = expr();
    jj_consume_token(26);
    thenBody = stmt();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      elseBody = stmt();
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
            {if (true) return new IfNode(location(t), cond, thenBody, elseBody);}
    throw new Error("Missing return statement in function");
  }

  final public WhileNode while_stmt() throws ParseException {
    Token t;
    ExprNode cond;
    StmtNode body;
    t = jj_consume_token(WHILE);
    jj_consume_token(33);
    cond = expr();
    jj_consume_token(26);
    body = stmt();
            {if (true) return new WhileNode(location(t), cond, body);}
    throw new Error("Missing return statement in function");
  }

  final public ForNode for_stmt() throws ParseException {
    Token t;
    ExprNode init = null, cond = null, incr = null;
    StmtNode body;
    t = jj_consume_token(FOR);
    jj_consume_token(33);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
    case TRUE:
    case FALSE:
    case NEW:
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 33:
    case 58:
    case 59:
    case 63:
    case 64:
    case 65:
    case 66:
      init = expr();
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
    jj_consume_token(32);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
    case TRUE:
    case FALSE:
    case NEW:
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 33:
    case 58:
    case 59:
    case 63:
    case 64:
    case 65:
    case 66:
      cond = expr();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(32);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
    case TRUE:
    case FALSE:
    case NEW:
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 33:
    case 58:
    case 59:
    case 63:
    case 64:
    case 65:
    case 66:
      incr = expr();
      break;
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    jj_consume_token(26);
    body = stmt();
            {if (true) return new ForNode(location(t), init, cond, incr, body);}
    throw new Error("Missing return statement in function");
  }

  final public BreakNode break_stmt() throws ParseException {
  Token t;
    t = jj_consume_token(BREAK);
    jj_consume_token(32);
                    {if (true) return new BreakNode(location(t));}
    throw new Error("Missing return statement in function");
  }

  final public ContinueNode continue_stmt() throws ParseException {
  Token t;
    t = jj_consume_token(CONTINUE);
    jj_consume_token(32);
                       {if (true) return new ContinueNode(location(t));}
    throw new Error("Missing return statement in function");
  }

  final public ReturnNode return_stmt() throws ParseException {
    Token t;
    ExprNode expr;
    if (jj_2_6(2)) {
      t = jj_consume_token(RETURN);
      jj_consume_token(32);
                                    {if (true) return new ReturnNode(location(t), null);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case RETURN:
        t = jj_consume_token(RETURN);
        expr = expr();
        jj_consume_token(32);
                                    {if (true) return new ReturnNode(location(t), expr);}
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr() throws ParseException {
    ExprNode lhs, rhs, expr;
    String op;
    if (jj_2_7(2147483647)) {
      lhs = term();
      jj_consume_token(34);
      rhs = expr();
            {if (true) return new AssignNode(lhs, rhs);}
    } else if (jj_2_8(2147483647)) {
      lhs = term();
      op = opassign_op();
      rhs = expr();
            {if (true) return new OpAssignNode(lhs, op, rhs);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NULL:
      case TRUE:
      case FALSE:
      case NEW:
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 33:
      case 58:
      case 59:
      case 63:
      case 64:
      case 65:
      case 66:
        expr = expr9();
            {if (true) return expr;}
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String opassign_op() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 35:
      jj_consume_token(35);
              {if (true) return "+";}
      break;
    case 36:
      jj_consume_token(36);
              {if (true) return "-";}
      break;
    case 37:
      jj_consume_token(37);
              {if (true) return "*";}
      break;
    case 38:
      jj_consume_token(38);
              {if (true) return "/";}
      break;
    case 39:
      jj_consume_token(39);
              {if (true) return "%";}
      break;
    case 40:
      jj_consume_token(40);
              {if (true) return "&";}
      break;
    case 41:
      jj_consume_token(41);
              {if (true) return "|";}
      break;
    case 42:
      jj_consume_token(42);
              {if (true) return "^";}
      break;
    case 43:
      jj_consume_token(43);
              {if (true) return "<<";}
      break;
    case 44:
      jj_consume_token(44);
              {if (true) return ">>";}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr9() throws ParseException {
  ExprNode l, r;
    l = expr8();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 45:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_7;
      }
      jj_consume_token(45);
      r = expr8();
                                l = new LogicalOrNode(l, r);
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr8() throws ParseException {
  ExprNode l, r;
    l = expr7();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 46:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_8;
      }
      jj_consume_token(46);
      r = expr7();
                                l = new LogicalAndNode(l, r);
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr7() throws ParseException {
  ExprNode l, r;
    l = expr6();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 47:
      case 48:
      case 49:
      case 50:
      case 51:
      case 52:
        ;
        break;
      default:
        jj_la1[18] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 47:
        jj_consume_token(47);
        r = expr6();
                                 l = new BinaryOpNode(l, ">", r);
        break;
      case 48:
        jj_consume_token(48);
        r = expr6();
                                 l = new BinaryOpNode(l, "<", r);
        break;
      case 49:
        jj_consume_token(49);
        r = expr6();
                                 l = new BinaryOpNode(l, ">=", r);
        break;
      case 50:
        jj_consume_token(50);
        r = expr6();
                                 l = new BinaryOpNode(l, "<=", r);
        break;
      case 51:
        jj_consume_token(51);
        r = expr6();
                                 l = new BinaryOpNode(l, "==", r);
        break;
      case 52:
        jj_consume_token(52);
        r = expr6();
                                 l = new BinaryOpNode(l, "!=", r);
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr6() throws ParseException {
  ExprNode l, r;
    l = expr5();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 53:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_10;
      }
      jj_consume_token(53);
      r = expr5();
                               l = new BinaryOpNode(l, "|", r);
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr5() throws ParseException {
  ExprNode l, r;
    l = expr4();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 54:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_11;
      }
      jj_consume_token(54);
      r = expr4();
                               l = new BinaryOpNode(l, "^", r);
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr4() throws ParseException {
  ExprNode l, r;
    l = expr3();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 55:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_12;
      }
      jj_consume_token(55);
      r = expr3();
                               l = new BinaryOpNode(l, "&", r);
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr3() throws ParseException {
  ExprNode l, r;
    l = expr2();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 56:
      case 57:
        ;
        break;
      default:
        jj_la1[23] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 56:
        jj_consume_token(56);
        r = expr2();
                                 l = new BinaryOpNode(l, ">>", r);
        break;
      case 57:
        jj_consume_token(57);
        r = expr2();
                                 l = new BinaryOpNode(l, "<<", r);
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr2() throws ParseException {
  ExprNode l, r;
    l = expr1();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 58:
      case 59:
        ;
        break;
      default:
        jj_la1[25] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 58:
        jj_consume_token(58);
        r = expr1();
                                l = new BinaryOpNode(l, "+", r);
        break;
      case 59:
        jj_consume_token(59);
        r = expr1();
                                l = new BinaryOpNode(l, "-", r);
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode expr1() throws ParseException {
  ExprNode l, r;
    l = term();
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 60:
      case 61:
      case 62:
        ;
        break;
      default:
        jj_la1[27] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 60:
        jj_consume_token(60);
        r = term();
                              l = new BinaryOpNode(l, "*", r);
        break;
      case 61:
        jj_consume_token(61);
        r = term();
                              l = new BinaryOpNode(l, "/", r);
        break;
      case 62:
        jj_consume_token(62);
        r = term();
                              l = new BinaryOpNode(l, "%", r);
        break;
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode term() throws ParseException {
    TypeNode t;
    ExprNode n;
    n = unary();
                                    {if (true) return n;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode unary() throws ParseException {
    ExprNode n;
    TypeNode t;
    List<ExprNode> args;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 63:
      jj_consume_token(63);
      n = unary();
                          {if (true) return new PrefixOpNode("++", n);}
      break;
    case 64:
      jj_consume_token(64);
      n = unary();
                          {if (true) return new PrefixOpNode("--", n);}
      break;
    case 58:
      jj_consume_token(58);
      n = term();
                          {if (true) return new UnaryOpNode("+", n);}
      break;
    case 59:
      jj_consume_token(59);
      n = term();
                          {if (true) return new UnaryOpNode("-", n);}
      break;
    case 65:
      jj_consume_token(65);
      n = term();
                          {if (true) return new UnaryOpNode("!", n);}
      break;
    case 66:
      jj_consume_token(66);
      n = term();
                          {if (true) return new UnaryOpNode("~", n);}
      break;
    case NEW:
      jj_consume_token(NEW);
      t = newtype();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        jj_consume_token(33);
        args = args();
        jj_consume_token(26);
        break;
      default:
        jj_la1[29] = jj_gen;
        ;
      }
                          {if (true) return new NewTypeNode(t);}
      break;
    case NULL:
    case TRUE:
    case FALSE:
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 33:
      n = postfix();
                          {if (true) return n;}
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ExprNode postfix() throws ParseException {
        Token t;
    ExprNode expr, idx, membfunc;
    String memb;
    List<ExprNode> args;
    expr = primary();
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 30:
      case 33:
      case 63:
      case 64:
      case 67:
        ;
        break;
      default:
        jj_la1[31] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 63:
        jj_consume_token(63);
                              expr = new SuffixOpNode("++", expr);
        break;
      case 64:
        jj_consume_token(64);
                              expr = new SuffixOpNode("--", expr);
        break;
      case 30:
        jj_consume_token(30);
        idx = expr();
        jj_consume_token(31);
                              expr = new ArefNode(expr, idx);
        break;
      default:
        jj_la1[32] = jj_gen;
        if (jj_2_9(3)) {
          t = jj_consume_token(67);
          membfunc = primary();
          jj_consume_token(33);
          args = args();
          jj_consume_token(26);
                                                  args.add(expr);
                                                ((VariableNode)membfunc).setName("." + ((VariableNode)membfunc).name());
                                                ((VariableNode)membfunc).setMemFuncBase(expr);
                                                  expr = new FuncallNode(membfunc, args, true);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 67:
            jj_consume_token(67);
            memb = name();
                              expr = new MemberNode(expr, memb);
            break;
          case 33:
            jj_consume_token(33);
            args = args();
            jj_consume_token(26);
                              expr = new FuncallNode(expr, args);
            break;
          default:
            jj_la1[33] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
            {if (true) return expr;}
    throw new Error("Missing return statement in function");
  }

  final public String name() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
                     if (t.image.equals("this")) {if (true) throw new Error("Gzotpa! Variable/function name cannot be \"this\"!");}
                    if (!isLetter(t.image.charAt(0))) {if (true) throw new Error("Gzotpa! Variable/function name must begin with a letter!");}
                                {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final public List<ExprNode> args() throws ParseException {
    List<ExprNode> args = new ArrayList<ExprNode>();
    ExprNode arg;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
    case TRUE:
    case FALSE:
    case NEW:
    case IDENTIFIER:
    case INTEGER:
    case STRING:
    case 33:
    case 58:
    case 59:
    case 63:
    case 64:
    case 65:
    case 66:
      arg = expr();
                   args.add(arg);
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 27:
          ;
          break;
        default:
          jj_la1[34] = jj_gen;
          break label_17;
        }
        jj_consume_token(27);
        arg = expr();
                        args.add(arg);
      }
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
            {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  final public ExprNode primary() throws ParseException {
    Token t;
    ExprNode n;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
      t = jj_consume_token(NULL);
                        {if (true) return new NullNode(location(t));}
      break;
    case TRUE:
      t = jj_consume_token(TRUE);
            {if (true) return new IntegerLiteralNode(location(t), IntegerTypeRef.intRef(true), integerValue("1"));}
      break;
    case FALSE:
      t = jj_consume_token(FALSE);
            {if (true) return new IntegerLiteralNode(location(t), IntegerTypeRef.intRef(true), integerValue("0"));}
      break;
    case INTEGER:
      t = jj_consume_token(INTEGER);
            {if (true) return new IntegerLiteralNode(location(t), IntegerTypeRef.intRef(), integerValue(t.image));}
      break;
    case STRING:
      t = jj_consume_token(STRING);
            {if (true) return new StringLiteralNode(location(t),
                new StringTypeRef(stringValue(t.image), location(t)),
                stringValue(t.image),
                t.image.substring(1, t.image.length() - 1));}
      break;
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
            {if (true) return new VariableNode(location(t), t.image);}
      break;
    case 33:
      jj_consume_token(33);
      n = expr();
      jj_consume_token(26);
            {if (true) return n;}
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public DefinedVariable defvar() throws ParseException {
        DefinedVariable var;
        TypeNode type;
        String name;
        ExprNode init = null;
    type = type();
    name = name();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 34:
      jj_consume_token(34);
      init = expr();
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
                        var = new DefinedVariable(type, name, init);
                        init = null;
    jj_consume_token(32);
                        {if (true) return var;}
    throw new Error("Missing return statement in function");
  }

  final public Declarations class_defs(String name) throws ParseException {
        Declarations decls = new Declarations();
        DefinedFunction defun;
    DefinedVariable defvar;
    jj_consume_token(28);
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case BOOL:
      case INT:
      case STR:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_18;
      }
      if (jj_2_10(2147483647)) {
        defun = defun();
                                          decls.addDefun(defun);
      } else if (jj_2_11(2147483647)) {
        defun = deconstruct(name);
                                          decls.addDefun(defun);
      } else if (jj_2_12(3)) {
        defvar = defvar();
                                  decls.addDefvar(defvar);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(29);
                {if (true) return decls;}
    throw new Error("Missing return statement in function");
  }

  final public ClassNode defclass() throws ParseException {
    Token t;
        String n;
    Declarations decls;
    t = jj_consume_token(CLASS);
    n = name();
    decls = class_defs(n);
        if (n.equals("main")) {
            {if (true) throw new Error("Gzotpa! Class name cannot be \"main\"!");}
        }
                {if (true) return new ClassNode(location(t), new ClassTypeRef(n), n, decls);}
    throw new Error("Missing return statement in function");
  }

  final public DefinedFunction deconstruct(String name) throws ParseException {
        Token t;
        String n;
        Params params;
        BlockNode body;
    n = name();
    t = jj_consume_token(33);
    params = params();
    jj_consume_token(26);
    body = block();
                if (!n.equals(name)) {if (true) throw new ParseException("Gzotpa! Wrong construction function!");}
                TypeRef tr = new FunctionTypeRef(new VoidTypeRef(location(t)), params.parametersTypeRef());
                {if (true) return new DefinedFunction(new TypeNode(tr), n, params, body, true);}
    throw new Error("Missing return statement in function");
  }

  final public DefinedFunction defun() throws ParseException {
        TypeRef ret;
        String n;
        Params params;
        BlockNode body;
    ret = typeref();
    n = name();
    jj_consume_token(33);
    params = params();
    jj_consume_token(26);
    body = block();
                        if (n.equals("main") && !(ret instanceof IntegerTypeRef)) {
                                {if (true) throw new Error("Gzotpa! Main function must return integer!");}
                        }
                        TypeRef t = new FunctionTypeRef(ret, params.parametersTypeRef());
                        {if (true) return new DefinedFunction(new TypeNode(t), n, params, body);}
    throw new Error("Missing return statement in function");
  }

  final public Declarations top_defs() throws ParseException {
        Declarations decls = new Declarations();
        DefinedFunction defun;
    ClassNode defclass;
        DefinedVariable defvar;
    label_19:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
      case BOOL:
      case INT:
      case STR:
      case CLASS:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[39] = jj_gen;
        break label_19;
      }
      if (jj_2_13(2147483647)) {
        defclass = defclass();
                                      decls.addDefclass(defclass);
      } else if (jj_2_14(2147483647)) {
        defun = defun();
                                if (defun.name().equals("main")) mainFunc = true;
                                                decls.addDefun(defun);
      } else if (jj_2_15(3)) {
        defvar = defvar();
                                  if (!mainFunc) decls.addDefvar(defvar);
                                                        else decls.addDefvaraftermain(defvar);
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
                        {if (true) return decls;}
    throw new Error("Missing return statement in function");
  }

  final public AST compilation_unit() throws ParseException {
        Token t;
        Declarations decls;
                t = getToken(1);
    decls = top_defs();
    jj_consume_token(0);
                        if (!mainFunc) {if (true) throw new Error("Gzotpa! No main function!");}
                        {if (true) return new AST(location(t), decls);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_3_6() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(27)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_87() {
    if (jj_scan_token(27)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_87()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_74() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_79()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_scan_token(33)) return true;
    if (jj_3R_74()) return true;
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_scan_token(33)) return true;
    if (jj_3R_74()) return true;
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_scan_token(67)) return true;
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_scan_token(67)) return true;
    if (jj_3R_25()) return true;
    if (jj_scan_token(33)) return true;
    if (jj_3R_74()) return true;
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_scan_token(30)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(64)) return true;
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_scan_token(63)) return true;
    return false;
  }

  private boolean jj_3R_75() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_80()) {
    jj_scanpos = xsp;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) {
    jj_scanpos = xsp;
    if (jj_3R_84()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_3R_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_75()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_14() {
    if (jj_3R_26()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(CLASS)) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_69()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(66)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(65)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_scan_token(58)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(64)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(63)) return true;
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_111() {
    if (jj_scan_token(62)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_110() {
    if (jj_scan_token(61)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_109() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_106() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_109()) {
    jj_scanpos = xsp;
    if (jj_3R_110()) {
    jj_scanpos = xsp;
    if (jj_3R_111()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_108() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_101()) return true;
    return false;
  }

  private boolean jj_3R_107() {
    if (jj_scan_token(58)) return true;
    if (jj_3R_101()) return true;
    return false;
  }

  private boolean jj_3R_103() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_107()) {
    jj_scanpos = xsp;
    if (jj_3R_108()) return true;
    }
    return false;
  }

  private boolean jj_3R_101() {
    if (jj_3R_23()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_106()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_105() {
    if (jj_scan_token(57)) return true;
    if (jj_3R_99()) return true;
    return false;
  }

  private boolean jj_3R_104() {
    if (jj_scan_token(56)) return true;
    if (jj_3R_99()) return true;
    return false;
  }

  private boolean jj_3R_102() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_104()) {
    jj_scanpos = xsp;
    if (jj_3R_105()) return true;
    }
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_99() {
    if (jj_3R_101()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_103()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(STR)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(BOOL)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  private boolean jj_3R_100() {
    if (jj_scan_token(55)) return true;
    if (jj_3R_97()) return true;
    return false;
  }

  private boolean jj_3R_97() {
    if (jj_3R_99()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_102()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_98() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_89()) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_3R_97()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_100()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(53)) return true;
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(30)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_26()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_3R_89()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_98()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_3R_51()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_5()) { jj_scanpos = xsp; break; }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_78()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(34)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_96() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_95() {
    if (jj_scan_token(51)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_scan_token(50)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_scan_token(49)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(48)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_3R_86()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_90()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_scan_token(47)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_88() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(46)) return true;
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(INTEGER)) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_3R_77()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_88()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(30)) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) return true;
    }
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(45)) return true;
    if (jj_3R_68()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_3R_51()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_52()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_27()) return true;
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) jj_scanpos = xsp;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_3R_72()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_85()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_68()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_76()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(44)) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(43)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(42)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(33)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(41)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(40)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(39)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(38)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(37)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(36)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(35)) return true;
    return false;
  }

  private boolean jj_3R_24() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_23()) return true;
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_23()) return true;
    if (jj_scan_token(34)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_23()) return true;
    if (jj_3R_24()) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_23()) return true;
    if (jj_scan_token(34)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    }
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[40];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x200ca,0x1207fafe,0x1207fa34,0x40000000,0x40000000,0x40000000,0x200ca,0x1207fa34,0x1207fa34,0x400,0x2070034,0x2070034,0x2070034,0x2000,0x2070034,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2070034,0x40000000,0x40000000,0x0,0x8000000,0x2070034,0x2060034,0x0,0x200ca,0x201ca,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x8c000003,0x8c000003,0x0,0x0,0x0,0x0,0x8c000003,0x8c000003,0x0,0x8c000002,0x8c000002,0x8c000002,0x0,0x8c000002,0x1ff8,0x2000,0x4000,0x1f8000,0x1f8000,0x200000,0x400000,0x800000,0x3000000,0x3000000,0xc000000,0xc000000,0x70000000,0x70000000,0x2,0x8c000002,0x80000002,0x80000000,0x2,0x0,0x8c000002,0x2,0x4,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x7,0x7,0x0,0x0,0x0,0x0,0x7,0x7,0x0,0x7,0x7,0x7,0x0,0x7,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7,0x9,0x1,0x8,0x0,0x7,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[15];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 40; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 40; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 40; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 40; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 40; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 40; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[68];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 40; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 68; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 15; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
