/* Generated By:JavaCC: Do not edit this line. Parser.java */
import java.io.*;

class Parser implements ParserConstants {
        static public void main(String[] args) {
                for (String arg : args) {
                        try {
                                System.out.println(evaluate(arg));
                        }
                        catch (ParseException ex) {
                                System.err.println(ex.getMessage());
                        }
                }
        }
        static public long evaluate(String src) throws ParseException {
                Reader reader = new StringReader(src);
                return new Parser(reader).expr();
        }
        private String sourceName;
        private LibraryLoader loader;
        private ErrorHandler errorHandler;
        private Set<String> knownTypedefs;
        public Parser(Reader s, String name, LibraryLoader loader,
        ErrorHandler errorHandler, boolean debug) {
                this(s);
                this.sourceName = name;
                this.loader = loader;
                this.errorHandler = errorHandler;
                this.knownTypedefs = new HashSet<String>();
                if (debug) {
                        enable_tracing();
                }
                else {
                        disable_tracing();
                }
        }
        static public AST parseFile(File file, LibraryLoader loader,
        ErrorHandler errorHandler, boolean debug)
        throws SyntaxException, FileException {
                return newFileParser(file, loader, errorHandler, debug).parse();
        }
        static final public String SOURCE_ENCODING = "UTF-8";
        static public Parser newFileParser(File file,
        LibraryLoader loader,
        ErrorHandler errorHandler,
        boolean debug)
        throws FileException {
                try {
                        BufferedReader r =
                        new BufferedReader(
                        new InputStreamReader(new FileInputStream(file),
                        SOURCE_ENCODING));
                        return new Parser(r, file.getPath(), loader, errorHandler, debug);
                }
                catch (FileNotFoundException ex) {
                        throw new FileException(ex.getMessage());
                }
                catch (UnsupportedEncodingException ex) {
                        throw new Error("UTF-8 is not supported??: " + ex.getMessage());
                }
        }
        public AST parse() throws SyntaxException {
                try {
                        return compilation_unit();
                }
                catch (TokenMgrError err) {
                        throw new SyntaxException(err.getMessage());
                }
                catch (ParseException ex) {
                        throw new SyntaxException(ex.getMessage());
                }
                catch (LookaheadSuccess err) {
                        throw new SyntaxException("syntax error");
                }
        }

  final public Params params() throws ParseException {
    trace_call("params");
    try {
    Token t;
    Params params;
      if (jj_2_1(2147483647)) {
        t = jj_consume_token(VOID);
            {if (true) return new Params(location(t), new ArrayList<Parameter>());}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VOID:
        case INT:
        case STRING:
          params = fixedparams();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 25:
            jj_consume_token(25);
            jj_consume_token(26);
                         params.acceptVarargs();
            break;
          default:
            jj_la1[0] = jj_gen;
            ;
          }
            {if (true) return params;}
          break;
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("params");
    }
  }

  final public Params fixedparams() throws ParseException {
    trace_call("fixedparams");
    try {
    List<Parameter> params = new ArrayList<Parameter>();
    Parameter param, param1;
      param1 = param();
                     params.add(param1);
      label_1:
      while (true) {
        if (jj_2_2(2)) {
          ;
        } else {
          break label_1;
        }
        jj_consume_token(25);
        param = param();
                                       params.add(param);
      }
            {if (true) return new Params(param1.location(), params);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("fixedparams");
    }
  }

  final public Parameter param() throws ParseException {
    trace_call("param");
    try {
    TypeNode t;
    String n;
      t = type();
      n = name();
                        {if (true) return new Parameter(t, n);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("param");
    }
  }

  final public BlockNode block() throws ParseException {
    trace_call("block");
    try {
    Token t;
    List<DefinedVariable> vars;
    List<StmtNode> stmts;
      t = jj_consume_token(27);
      vars = defvar_list();
      stmts = stmts();
      jj_consume_token(28);
            {if (true) return new BlockNode(location(t), vars, stmts);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("block");
    }
  }

  final public TypeNode type() throws ParseException {
    trace_call("type");
    try {
  TypeRef ref;
      ref = typeref();
                    {if (true) return new TypeNode(ref);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("type");
    }
  }

  final public TypeRef typeref() throws ParseException {
    trace_call("typeref");
    try {
    TypeRef ref;
    ParamTypeRefs params;
      ref = typeref_base();
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 29:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_2;
        }
        jj_consume_token(29);
        jj_consume_token(30);
            ref = new ArrayTypeRef(ref);
      }
            {if (true) return ref;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("typeref");
    }
  }

  final public TypeRef typeref_base() throws ParseException {
    trace_call("typeref_base");
    try {
    Token t;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
        t = jj_consume_token(VOID);
                          {if (true) return new VoidTypeRef(location(t));}
        break;
      case INT:
        t = jj_consume_token(INT);
                          {if (true) return IntegerTypeRef.intRef(location(t));}
        break;
      case STRING:
        t = jj_consume_token(STRING);
                          {if (true) return StringTypeRef.intRef(location(t));}
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("typeref_base");
    }
  }

  final public List<StmtNode> stmts() throws ParseException {
    trace_call("stmts");
    try {
    List<StmtNode> ss = new ArrayList<StmtNode>();
    StmtNode s;
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
        case WHILE:
        case FOR:
        case RETURN:
        case BREAK:
        case CONTINUE:
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 27:
        case 31:
        case 32:
        case 54:
        case 57:
        case 58:
        case 59:
        case 62:
        case 63:
        case 64:
        case 65:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        s = stmt();
                if (s != null) ss.add(s);
      }
            {if (true) return ss;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("stmts");
    }
  }

  final public StmtNode stmt() throws ParseException {
    trace_call("stmt");
    try {
    StmtNode n = null;
    ExprNode e = null;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 31:
        jj_consume_token(31);
        break;
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 54:
      case 57:
      case 58:
      case 59:
      case 62:
      case 63:
      case 64:
      case 65:
        e = expr();
        jj_consume_token(31);
                     n = new ExprStmtNode(e.location(), e);
        break;
      case 27:
        n = block();
        break;
      case IF:
        n = if_stmt();
        break;
      case WHILE:
        n = while_stmt();
        break;
      case FOR:
        n = for_stmt();
        break;
      case BREAK:
        n = break_stmt();
        break;
      case CONTINUE:
        n = continue_stmt();
        break;
      case RETURN:
        n = return_stmt();
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
            {if (true) return n;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("stmt");
    }
  }

  final public IfNode if_stmt() throws ParseException {
    trace_call("if_stmt");
    try {
    Token t;
    ExprNode cond;
    StmtNode thenBody, elseBody = null;
      t = jj_consume_token(IF);
      jj_consume_token(32);
      cond = expr();
      jj_consume_token(24);
      thenBody = stmt();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
        elseBody = stmt();
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
            {if (true) return new IfNode(location(t), cond, thenBody, elseBody);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("if_stmt");
    }
  }

  final public WhileNode while_stmt() throws ParseException {
    trace_call("while_stmt");
    try {
    Token t;
    ExprNode cond;
    StmtNode body;
      t = jj_consume_token(WHILE);
      jj_consume_token(32);
      cond = expr();
      jj_consume_token(24);
      body = stmt();
            {if (true) return new WhileNode(location(t), cond, body);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("while_stmt");
    }
  }

  final public ForNode for_stmt() throws ParseException {
    trace_call("for_stmt");
    try {
    Token t;
    ExprNode init = null, cond = null, incr = null;
    StmtNode body;
      t = jj_consume_token(FOR);
      jj_consume_token(32);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 54:
      case 57:
      case 58:
      case 59:
      case 62:
      case 63:
      case 64:
      case 65:
        init = expr();
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(31);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 54:
      case 57:
      case 58:
      case 59:
      case 62:
      case 63:
      case 64:
      case 65:
        cond = expr();
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      jj_consume_token(31);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 54:
      case 57:
      case 58:
      case 59:
      case 62:
      case 63:
      case 64:
      case 65:
        incr = expr();
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      jj_consume_token(24);
      body = stmt();
            {if (true) return new ForNode(location(t), init, cond, incr, body);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("for_stmt");
    }
  }

  final public BreakNode break_stmt() throws ParseException {
    trace_call("break_stmt");
    try {
  Token t;
      t = jj_consume_token(BREAK);
      jj_consume_token(31);
                    {if (true) return new BreakNode(location(t));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("break_stmt");
    }
  }

  final public ContinueNode continue_stmt() throws ParseException {
    trace_call("continue_stmt");
    try {
  Token t;
      t = jj_consume_token(CONTINUE);
      jj_consume_token(31);
                       {if (true) return new ContinueNode(location(t));}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("continue_stmt");
    }
  }

  final public ReturnNode return_stmt() throws ParseException {
    trace_call("return_stmt");
    try {
    Token t;
    ExprNode expr;
      if (jj_2_3(2)) {
        t = jj_consume_token(RETURN);
        jj_consume_token(31);
                                    {if (true) return new ReturnNode(location(t), null);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RETURN:
          t = jj_consume_token(RETURN);
          expr = expr();
          jj_consume_token(31);
                                    {if (true) return new ReturnNode(location(t), expr);}
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("return_stmt");
    }
  }

  final public ExprNode expr() throws ParseException {
    trace_call("expr");
    try {
    ExprNode lhs, rhs, expr;
    String op;
      if (jj_2_4(2147483647)) {
        lhs = term();
        jj_consume_token(33);
        rhs = expr();
            {if (true) return new AssignNode(lhs, rhs);}
      } else if (jj_2_5(2147483647)) {
        lhs = term();
        op = opassign_op();
        rhs = expr();
            {if (true) return new OpAssignNode(lhs, op, rhs);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 32:
        case 54:
        case 57:
        case 58:
        case 59:
        case 62:
        case 63:
        case 64:
        case 65:
          expr = expr9();
            {if (true) return expr;}
          break;
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr");
    }
  }

  final public String opassign_op() throws ParseException {
    trace_call("opassign_op");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        jj_consume_token(34);
              {if (true) return "+";}
        break;
      case 35:
        jj_consume_token(35);
              {if (true) return "-";}
        break;
      case 36:
        jj_consume_token(36);
              {if (true) return "*";}
        break;
      case 37:
        jj_consume_token(37);
              {if (true) return "/";}
        break;
      case 38:
        jj_consume_token(38);
              {if (true) return "%";}
        break;
      case 39:
        jj_consume_token(39);
              {if (true) return "&";}
        break;
      case 40:
        jj_consume_token(40);
              {if (true) return "|";}
        break;
      case 41:
        jj_consume_token(41);
              {if (true) return "^";}
        break;
      case 42:
        jj_consume_token(42);
              {if (true) return "<<";}
        break;
      case 43:
        jj_consume_token(43);
              {if (true) return ">>";}
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("opassign_op");
    }
  }

  final public ExprNode expr9() throws ParseException {
    trace_call("expr9");
    try {
  ExprNode l, r;
      l = expr8();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 44:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_4;
        }
        jj_consume_token(44);
        r = expr8();
                                l = new LogicalOrNode(l, r);
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr9");
    }
  }

  final public ExprNode expr8() throws ParseException {
    trace_call("expr8");
    try {
  ExprNode l, r;
      l = expr7();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_5;
        }
        jj_consume_token(45);
        r = expr7();
                                l = new LogicalAndNode(l, r);
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr8");
    }
  }

  final public ExprNode expr7() throws ParseException {
    trace_call("expr7");
    try {
  ExprNode l, r;
      l = expr6();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 46:
        case 47:
        case 48:
        case 49:
        case 50:
        case 51:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 46:
          jj_consume_token(46);
          r = expr6();
                                 l = new BinaryOpNode(l, ">", r);
          break;
        case 47:
          jj_consume_token(47);
          r = expr6();
                                 l = new BinaryOpNode(l, "<", r);
          break;
        case 48:
          jj_consume_token(48);
          r = expr6();
                                 l = new BinaryOpNode(l, ">=", r);
          break;
        case 49:
          jj_consume_token(49);
          r = expr6();
                                 l = new BinaryOpNode(l, "<=", r);
          break;
        case 50:
          jj_consume_token(50);
          r = expr6();
                                 l = new BinaryOpNode(l, "==", r);
          break;
        case 51:
          jj_consume_token(51);
          r = expr6();
                                 l = new BinaryOpNode(l, "!=", r);
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr7");
    }
  }

  final public ExprNode expr6() throws ParseException {
    trace_call("expr6");
    try {
  ExprNode l, r;
      l = expr5();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 52:
          ;
          break;
        default:
          jj_la1[17] = jj_gen;
          break label_7;
        }
        jj_consume_token(52);
        r = expr5();
                               l = new BinaryOpNode(l, "|", r);
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr6");
    }
  }

  final public ExprNode expr5() throws ParseException {
    trace_call("expr5");
    try {
  ExprNode l, r;
      l = expr4();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 53:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_8;
        }
        jj_consume_token(53);
        r = expr4();
                               l = new BinaryOpNode(l, "^", r);
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr5");
    }
  }

  final public ExprNode expr4() throws ParseException {
    trace_call("expr4");
    try {
  ExprNode l, r;
      l = expr3();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 54:
          ;
          break;
        default:
          jj_la1[19] = jj_gen;
          break label_9;
        }
        jj_consume_token(54);
        r = expr3();
                               l = new BinaryOpNode(l, "&", r);
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr4");
    }
  }

  final public ExprNode expr3() throws ParseException {
    trace_call("expr3");
    try {
  ExprNode l, r;
      l = expr2();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 55:
        case 56:
          ;
          break;
        default:
          jj_la1[20] = jj_gen;
          break label_10;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 55:
          jj_consume_token(55);
          r = expr2();
                                 l = new BinaryOpNode(l, ">>", r);
          break;
        case 56:
          jj_consume_token(56);
          r = expr2();
                                 l = new BinaryOpNode(l, "<<", r);
          break;
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr3");
    }
  }

  final public ExprNode expr2() throws ParseException {
    trace_call("expr2");
    try {
  ExprNode l, r;
      l = expr1();
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 57:
        case 58:
          ;
          break;
        default:
          jj_la1[22] = jj_gen;
          break label_11;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 57:
          jj_consume_token(57);
          r = expr1();
                                l = new BinaryOpNode(l, "+", r);
          break;
        case 58:
          jj_consume_token(58);
          r = expr1();
                                l = new BinaryOpNode(l, "-", r);
          break;
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr2");
    }
  }

  final public ExprNode expr1() throws ParseException {
    trace_call("expr1");
    try {
  ExprNode l, r;
      l = term();
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 59:
        case 60:
        case 61:
          ;
          break;
        default:
          jj_la1[24] = jj_gen;
          break label_12;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 59:
          jj_consume_token(59);
          r = term();
                              l = new BinaryOpNode(l, "*", r);
          break;
        case 60:
          jj_consume_token(60);
          r = term();
                              l = new BinaryOpNode(l, "/", r);
          break;
        case 61:
          jj_consume_token(61);
          r = term();
                              l = new BinaryOpNode(l, "%", r);
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
            {if (true) return l;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expr1");
    }
  }

  final public ExprNode term() throws ParseException {
    trace_call("term");
    try {
    TypeNode t;
    ExprNode n;
      if (jj_2_6(2147483647)) {
        jj_consume_token(32);
        t = type();
        jj_consume_token(24);
        n = term();
                                      {if (true) return new CastNode(t, n);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 32:
        case 54:
        case 57:
        case 58:
        case 59:
        case 62:
        case 63:
        case 64:
        case 65:
          n = unary();
                                      {if (true) return n;}
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("term");
    }
  }

  final public ExprNode unary() throws ParseException {
    trace_call("unary");
    try {
    ExprNode n;
    TypeNode t;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 62:
        jj_consume_token(62);
        n = unary();
                          {if (true) return new PrefixOpNode("++", n);}
        break;
      case 63:
        jj_consume_token(63);
        n = unary();
                          {if (true) return new PrefixOpNode("--", n);}
        break;
      case 57:
        jj_consume_token(57);
        n = term();
                          {if (true) return new UnaryOpNode("+", n);}
        break;
      case 58:
        jj_consume_token(58);
        n = term();
                          {if (true) return new UnaryOpNode("-", n);}
        break;
      case 64:
        jj_consume_token(64);
        n = term();
                          {if (true) return new UnaryOpNode("!", n);}
        break;
      case 65:
        jj_consume_token(65);
        n = term();
                          {if (true) return new UnaryOpNode("~", n);}
        break;
      case 59:
        jj_consume_token(59);
        n = term();
                          {if (true) return new DereferenceNode(n);}
        break;
      case 54:
        jj_consume_token(54);
        n = term();
                          {if (true) return new AddressNode(n);}
        break;
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
        n = postfix();
                          {if (true) return n;}
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("unary");
    }
  }

  final public ExprNode postfix() throws ParseException {
    trace_call("postfix");
    try {
    ExprNode expr, idx;
    String memb;
    List<ExprNode> args;
      expr = primary();
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 29:
        case 32:
        case 62:
        case 63:
          ;
          break;
        default:
          jj_la1[28] = jj_gen;
          break label_13;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 62:
          jj_consume_token(62);
                              expr = new SuffixOpNode("++", expr);
          break;
        case 63:
          jj_consume_token(63);
                              expr = new SuffixOpNode("--", expr);
          break;
        case 29:
          jj_consume_token(29);
          idx = expr();
          jj_consume_token(30);
                              expr = new ArefNode(expr, idx);
          break;
        case 32:
          jj_consume_token(32);
          args = args();
          jj_consume_token(24);
                              expr = new FuncallNode(expr, args);
          break;
        default:
          jj_la1[29] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
            {if (true) return expr;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("postfix");
    }
  }

  final public String name() throws ParseException {
    trace_call("name");
    try {
  Token t;
      t = jj_consume_token(IDENTIFIER);
                     {if (true) return t.image;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("name");
    }
  }

  final public List<ExprNode> args() throws ParseException {
    trace_call("args");
    try {
    List<ExprNode> args = new ArrayList<ExprNode>();
    ExprNode arg;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 54:
      case 57:
      case 58:
      case 59:
      case 62:
      case 63:
      case 64:
      case 65:
        arg = expr();
                   args.add(arg);
        label_14:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 25:
            ;
            break;
          default:
            jj_la1[30] = jj_gen;
            break label_14;
          }
          jj_consume_token(25);
          arg = expr();
                        args.add(arg);
        }
        break;
      default:
        jj_la1[31] = jj_gen;
        ;
      }
            {if (true) return args;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("args");
    }
  }

  final public ExprNode primary() throws ParseException {
    trace_call("primary");
    try {
    Token t;
    ExprNode n;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
        t = jj_consume_token(INTEGER);
            {if (true) return integerNode(location(t), t.image);}
        break;
      case STRING:
        t = jj_consume_token(STRING);
            {if (true) return new StringLiteralNode(location(t),
                new PointerTypeRef(IntegerTypeRef.charRef()),
                stringValue(t.image));}
        break;
      case IDENTIFIER:
        t = jj_consume_token(IDENTIFIER);
            {if (true) return new VariableNode(location(t), t.image);}
        break;
      case 32:
        jj_consume_token(32);
        n = expr();
        jj_consume_token(24);
            {if (true) return n;}
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("primary");
    }
  }

  final public List<DefinedVariable> defvars() throws ParseException {
    trace_call("defvars");
    try {
        List<DefinedVariable> defs = new ArrayList<DefinedVariable>();
        TypeNode type;
        String name;
        ExprNode init = null;
      type = type();
      name = name();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        jj_consume_token(33);
        init = expr();
        break;
      default:
        jj_la1[33] = jj_gen;
        ;
      }
                        defs.add(new DefinedVariable(type, name, init));
                        init = null;
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 25:
          ;
          break;
        default:
          jj_la1[34] = jj_gen;
          break label_15;
        }
        jj_consume_token(25);
        name = name();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 33:
          jj_consume_token(33);
          init = expr();
          break;
        default:
          jj_la1[35] = jj_gen;
          ;
        }
                        defs.add(new DefinedVariable(type, name, init));
                        init = null;
      }
      jj_consume_token(31);
                        {if (true) return defs;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defvars");
    }
  }

  final public DefinedFunction defun() throws ParseException {
    trace_call("defun");
    try {
        TypeRef ret;
        String n;
        Params ps;
        BlockNode body;
      ret = typeref();
      n = name();
      jj_consume_token(32);
      ps = params();
      jj_consume_token(24);
      body = block();
                        TypeRef t = new FunctionTypeRef(ret, ps.parametersTypeRef());
                        {if (true) return new DefinedFunction(new TypeNode(t), n, ps, body);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defun");
    }
  }

  final public List<DefinedVariable> defvar_list() throws ParseException {
    trace_call("defvar_list");
    try {
        List<DefinedVariable> result = new ArrayList<DefinedVariable>();
        List<DefinedVariable> vars;
      label_16:
      while (true) {
        if (jj_2_7(2)) {
          ;
        } else {
          break label_16;
        }
        vars = defvars();
                                        result.addAll(vars);
      }
                        {if (true) return result;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defvar_list");
    }
  }

  final public Declarations top_defs() throws ParseException {
    trace_call("top_defs");
    try {
        Declarations decls = new Declarations();
        DefinedFunction defun;
        List<DefinedVariable> defvars;
        Constant defconst;
        StructNode defstruct;
        UnionNode defunion;
        TypedefNode typedef;
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VOID:
        case INT:
        case STRING:
          ;
          break;
        default:
          jj_la1[36] = jj_gen;
          break label_17;
        }
        if (jj_2_8(2147483647)) {
          defun = defun();
                                decls.addDefun(defun);
        } else if (jj_2_9(3)) {
          defvars = defvars();
                                    decls.addDefvars(defvars);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
                        {if (true) return decls;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("top_defs");
    }
  }

  final public AST compilation_unit() throws ParseException {
    trace_call("compilation_unit");
    try {
        Token t;
        Declarations decls;
                t = getToken(1);
      decls = top_defs();
      jj_consume_token(0);
                        {if (true) return new AST(location(t), decls);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("compilation_unit");
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_3_8() {
    if (jj_3R_23()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3R_88() {
    if (jj_scan_token(53)) return true;
    if (jj_3R_87()) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(29)) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  private boolean jj_3R_87() {
    if (jj_3R_89()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_90()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_37()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_38()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_87()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_88()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(51)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(50)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_scan_token(49)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_scan_token(48)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_scan_token(47)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_3R_79()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_80()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(46)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_78() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) {
    jj_scanpos = xsp;
    if (jj_3R_84()) {
    jj_scanpos = xsp;
    if (jj_3R_85()) {
    jj_scanpos = xsp;
    if (jj_3R_86()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(45)) return true;
    if (jj_3R_75()) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_3R_77()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_78()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(25)) return true;
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_scan_token(44)) return true;
    if (jj_3R_73()) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_3R_75()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_76()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_3R_73()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_74()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(43)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(42)) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(41)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(40)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(39)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_scan_token(38)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(37)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(36)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(35)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_21()) return true;
    if (jj_3R_36()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_39()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_40()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(34)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_19()) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_3R_71()) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_3R_19()) return true;
    if (jj_3R_20()) return true;
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_65()) return true;
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_65() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_3R_19()) return true;
    if (jj_scan_token(33)) return true;
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_scan_token(25)) return true;
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_3R_65()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_72()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_66() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_66()) return true;
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_65()) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(63)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(62)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_55()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_56()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_54()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(65)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(64)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(58)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(57)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(63)) return true;
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(62)) return true;
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_19() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_21()) return true;
    if (jj_scan_token(24)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_102() {
    if (jj_scan_token(61)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_101() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_100() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_97() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_100()) {
    jj_scanpos = xsp;
    if (jj_3R_101()) {
    jj_scanpos = xsp;
    if (jj_3R_102()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_99() {
    if (jj_scan_token(58)) return true;
    if (jj_3R_93()) return true;
    return false;
  }

  private boolean jj_3R_98() {
    if (jj_scan_token(57)) return true;
    if (jj_3R_93()) return true;
    return false;
  }

  private boolean jj_3R_94() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_98()) {
    jj_scanpos = xsp;
    if (jj_3R_99()) return true;
    }
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_3R_19()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_97()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_96() {
    if (jj_scan_token(56)) return true;
    if (jj_3R_91()) return true;
    return false;
  }

  private boolean jj_3R_95() {
    if (jj_scan_token(55)) return true;
    if (jj_3R_91()) return true;
    return false;
  }

  private boolean jj_3R_92() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_95()) {
    jj_scanpos = xsp;
    if (jj_3R_96()) return true;
    }
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_3R_93()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_94()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_89()) return true;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_3R_91()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_92()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[37];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000000,0x800042,0x20000000,0x800042,0x8881fd00,0x8881fd00,0x200,0x818000,0x818000,0x818000,0x1000,0x818000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x818000,0x818000,0x20000000,0x20000000,0x2000000,0x818000,0x818000,0x0,0x2000000,0x0,0x800042,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0xce400001,0xce400001,0x0,0xce400001,0xce400001,0xce400001,0x0,0xce400001,0xffc,0x1000,0x2000,0xfc000,0xfc000,0x100000,0x200000,0x400000,0x1800000,0x1800000,0x6000000,0x6000000,0x38000000,0x38000000,0xce400001,0xce400001,0xc0000001,0xc0000001,0x0,0xce400001,0x1,0x2,0x0,0x2,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x3,0x3,0x0,0x3,0x3,0x3,0x0,0x3,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x3,0x0,0x0,0x0,0x3,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[9];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[66];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 37; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 66; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private int trace_indent = 0;
  private boolean trace_enabled = true;

/** Enable tracing. */
  final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
    trace_enabled = false;
  }

  private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 9; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
