/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VOID = 1;
  /** RegularExpression Id. */
  int NULL = 2;
  /** RegularExpression Id. */
  int BOOL = 3;
  /** RegularExpression Id. */
  int TRUE = 4;
  /** RegularExpression Id. */
  int FALSE = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CLASS = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int RETURN = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int CONTINUE = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;
  /** RegularExpression Id. */
  int INTEGER = 16;
  /** RegularExpression Id. */
  int SPACES = 17;
  /** RegularExpression Id. */
  int LINE_COMMENT = 18;
  /** RegularExpression Id. */
  int STRING = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"void\"",
    "\"null\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"int\"",
    "\"class\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<SPACES>",
    "<LINE_COMMENT>",
    "\"\\\"\"",
    "<token of kind 20>",
    "<token of kind 21>",
    "<token of kind 22>",
    "\"\\\"\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"...\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"~\"",
    "\".\"",
    "\"->\"",
  };

}
