/* Generated By:JavaCC: Do not edit this line. Parser.java */
import java.io.*;

class Parser implements ParserConstants {
        static public void main(String[] args) {
                for (String arg : args) {
                        try {
                                System.out.println(evaluate(arg));
                        }
                        catch (ParseException ex) {
                                System.err.println(ex.getMessage());
                        }
                }
        }
        static public long evaluate(String src) throws ParseException {
                Reader reader = new StringReader(src);
                return new Parser(reader).expr();
        }
        private String sourceName;
        private LibraryLoader loader;
        private ErrorHandler errorHandler;
        private Set<String> knownTypedefs;
        public Parser(Reader s, String name, LibraryLoader loader,
        ErrorHandler errorHandler, boolean debug) {
                this(s);
                this.sourceName = name;
                this.loader = loader;
                this.errorHandler = errorHandler;
                this.knownTypedefs = new HashSet<String>();
                if (debug) {
                        enable_tracing();
                }
                else {
                        disable_tracing();
                }
        }
        static public AST parseFile(File file, LibraryLoader loader,
        ErrorHandler errorHandler, boolean debug)
        throws SyntaxException, FileException {
                return newFileParser(file, loader, errorHandler, debug).parse();
        }
        static final public String SOURCE_ENCODING = "UTF-8";
        static public Parser newFileParser(File file,
        LibraryLoader loader,
        ErrorHandler errorHandler,
        boolean debug)
        throws FileException {
                try {
                        BufferedReader r =
                        new BufferedReader(
                        new InputStreamReader(new FileInputStream(file),
                        SOURCE_ENCODING));
                        return new Parser(r, file.getPath(), loader, errorHandler, debug);
                }
                catch (FileNotFoundException ex) {
                        throw new FileException(ex.getMessage());
                }
                catch (UnsupportedEncodingException ex) {
                        throw new Error("UTF-8 is not supported??: " + ex.getMessage());
                }
        }
        public AST parse() throws SyntaxException {
                try {
                        return compilation_unit();
                }
                catch (TokenMgrError err) {
                        throw new SyntaxException(err.getMessage());
                }
                catch (ParseException ex) {
                        throw new SyntaxException(ex.getMessage());
                }
                catch (LookaheadSuccess err) {
                        throw new SyntaxException("syntax error");
                }
        }

  final public String name() throws ParseException {
    trace_call("name");
    try {
    Token t;
      t = jj_consume_token(IDENTIFIER);
                     {if (true) return t.image;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("name");
    }
  }

  final public Params params() throws ParseException {
    trace_call("params");
    try {
    Token t;
    Params params;
      if (jj_2_1(2147483647)) {
        t = jj_consume_token(VOID);
            {if (true) return new Params(location(t), new ArrayList<Parameter>());}
      } else if (jj_2_2(1)) {
        params = fixedparams();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 25:
          jj_consume_token(25);
          jj_consume_token(26);
                         params.acceptVarargs();
          break;
        default:
          jj_la1[0] = jj_gen;
          ;
        }
            {if (true) return params;}
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("params");
    }
  }

  final public Params fixedparams() throws ParseException {
    trace_call("fixedparams");
    try {
    List<Parameter> params = new ArrayList<Parameter>();
    Parameter param, param1;
      param1 = param();
                     params.add(param1);
      label_1:
      while (true) {
        if (jj_2_3(2)) {
          ;
        } else {
          break label_1;
        }
        jj_consume_token(25);
        param = param();
                                       params.add(param);
      }
            {if (true) return new Params(param1.location(), params);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("fixedparams");
    }
  }

  final public Parameter param() throws ParseException {
    trace_call("param");
    try {
    TypeNode t;
    String n;
      t = type();
      n = name();
                        {if (true) return new Parameter(t, n);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("param");
    }
  }

  final public void block() throws ParseException {
    trace_call("block");
    try {
      jj_consume_token(27);
      defvar_list();
      stmts();
      jj_consume_token(28);
    } finally {
      trace_return("block");
    }
  }

  final public void type() throws ParseException {
    trace_call("type");
    try {
      typeref();
    } finally {
      trace_return("type");
    }
  }

  final public void typeref() throws ParseException {
    trace_call("typeref");
    try {
      typeref_base();
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 29:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
        if (jj_2_4(2)) {
          jj_consume_token(29);
          jj_consume_token(30);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 29:
            jj_consume_token(29);
            jj_consume_token(INTEGER);
            jj_consume_token(30);
            break;
          default:
            jj_la1[2] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    } finally {
      trace_return("typeref");
    }
  }

  final public void typeref_base() throws ParseException {
    trace_call("typeref_base");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
        jj_consume_token(VOID);
        break;
      case INT:
        jj_consume_token(INT);
        break;
      default:
        jj_la1[3] = jj_gen;
        if (isType(getToken(1).image)) {
          jj_consume_token(IDENTIFIER);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("typeref_base");
    }
  }

  final public void stmts() throws ParseException {
    trace_call("stmts");
    try {
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IF:
        case WHILE:
        case FOR:
        case RETURN:
        case BREAK:
        case CONTINUE:
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 27:
        case 31:
        case 32:
        case 56:
        case 59:
        case 60:
        case 61:
        case 64:
        case 65:
        case 66:
        case 67:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_3;
        }
        stmt();
      }
    } finally {
      trace_return("stmts");
    }
  }

  final public void stmt() throws ParseException {
    trace_call("stmt");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 31:
        jj_consume_token(31);
        break;
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 56:
      case 59:
      case 60:
      case 61:
      case 64:
      case 65:
      case 66:
      case 67:
        expr();
        jj_consume_token(31);
        break;
      case 27:
        block();
        break;
      case IF:
        if_stmt();
        break;
      case WHILE:
        while_stmt();
        break;
      case FOR:
        for_stmt();
        break;
      case BREAK:
        break_stmt();
        break;
      case CONTINUE:
        continue_stmt();
        break;
      case RETURN:
        return_stmt();
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("stmt");
    }
  }

  final public void if_stmt() throws ParseException {
    trace_call("if_stmt");
    try {
      jj_consume_token(IF);
      jj_consume_token(32);
      expr();
      jj_consume_token(24);
      stmt();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
        stmt();
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
    } finally {
      trace_return("if_stmt");
    }
  }

  final public void while_stmt() throws ParseException {
    trace_call("while_stmt");
    try {
      jj_consume_token(WHILE);
      jj_consume_token(32);
      expr();
      jj_consume_token(24);
      stmt();
    } finally {
      trace_return("while_stmt");
    }
  }

  final public void for_stmt() throws ParseException {
    trace_call("for_stmt");
    try {
      jj_consume_token(FOR);
      jj_consume_token(32);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 56:
      case 59:
      case 60:
      case 61:
      case 64:
      case 65:
      case 66:
      case 67:
        expr();
        break;
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(31);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 56:
      case 59:
      case 60:
      case 61:
      case 64:
      case 65:
      case 66:
      case 67:
        expr();
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      jj_consume_token(31);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 56:
      case 59:
      case 60:
      case 61:
      case 64:
      case 65:
      case 66:
      case 67:
        expr();
        break;
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      jj_consume_token(24);
      stmt();
    } finally {
      trace_return("for_stmt");
    }
  }

  final public void break_stmt() throws ParseException {
    trace_call("break_stmt");
    try {
      jj_consume_token(BREAK);
      jj_consume_token(31);
    } finally {
      trace_return("break_stmt");
    }
  }

  final public void continue_stmt() throws ParseException {
    trace_call("continue_stmt");
    try {
      jj_consume_token(CONTINUE);
      jj_consume_token(31);
    } finally {
      trace_return("continue_stmt");
    }
  }

  final public void return_stmt() throws ParseException {
    trace_call("return_stmt");
    try {
      if (jj_2_5(2)) {
        jj_consume_token(RETURN);
        jj_consume_token(31);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RETURN:
          jj_consume_token(RETURN);
          expr();
          jj_consume_token(31);
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("return_stmt");
    }
  }

  final public void expr() throws ParseException {
    trace_call("expr");
    try {
      if (jj_2_6(2147483647)) {
        term();
        jj_consume_token(33);
        expr();
      } else if (jj_2_7(2147483647)) {
        term();
        opassign_op();
        expr();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 32:
        case 56:
        case 59:
        case 60:
        case 61:
        case 64:
        case 65:
        case 66:
        case 67:
          expr10();
          break;
        default:
          jj_la1[11] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr");
    }
  }

  final public void opassign_op() throws ParseException {
    trace_call("opassign_op");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 34:
        jj_consume_token(34);
        break;
      case 35:
        jj_consume_token(35);
        break;
      case 36:
        jj_consume_token(36);
        break;
      case 37:
        jj_consume_token(37);
        break;
      case 38:
        jj_consume_token(38);
        break;
      case 39:
        jj_consume_token(39);
        break;
      case 40:
        jj_consume_token(40);
        break;
      case 41:
        jj_consume_token(41);
        break;
      case 42:
        jj_consume_token(42);
        break;
      case 43:
        jj_consume_token(43);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("opassign_op");
    }
  }

  final public void expr10() throws ParseException {
    trace_call("expr10");
    try {
      expr9();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 44:
        jj_consume_token(44);
        expr();
        jj_consume_token(45);
        expr10();
        break;
      default:
        jj_la1[13] = jj_gen;
        ;
      }
    } finally {
      trace_return("expr10");
    }
  }

  final public void expr9() throws ParseException {
    trace_call("expr9");
    try {
      expr8();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 46:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_4;
        }
        jj_consume_token(46);
        expr8();
      }
    } finally {
      trace_return("expr9");
    }
  }

  final public void expr8() throws ParseException {
    trace_call("expr8");
    try {
      expr7();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 47:
          ;
          break;
        default:
          jj_la1[15] = jj_gen;
          break label_5;
        }
        jj_consume_token(47);
        expr7();
      }
    } finally {
      trace_return("expr8");
    }
  }

  final public void expr7() throws ParseException {
    trace_call("expr7");
    try {
      expr6();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
          ;
          break;
        default:
          jj_la1[16] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 48:
          jj_consume_token(48);
          expr6();
          break;
        case 49:
          jj_consume_token(49);
          expr6();
          break;
        case 50:
          jj_consume_token(50);
          expr6();
          break;
        case 51:
          jj_consume_token(51);
          expr6();
          break;
        case 52:
          jj_consume_token(52);
          expr6();
          break;
        case 53:
          jj_consume_token(53);
          expr6();
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr7");
    }
  }

  final public void expr6() throws ParseException {
    trace_call("expr6");
    try {
      expr5();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 54:
          ;
          break;
        default:
          jj_la1[18] = jj_gen;
          break label_7;
        }
        jj_consume_token(54);
        expr5();
      }
    } finally {
      trace_return("expr6");
    }
  }

  final public void expr5() throws ParseException {
    trace_call("expr5");
    try {
      expr4();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 55:
          ;
          break;
        default:
          jj_la1[19] = jj_gen;
          break label_8;
        }
        jj_consume_token(55);
        expr4();
      }
    } finally {
      trace_return("expr5");
    }
  }

  final public void expr4() throws ParseException {
    trace_call("expr4");
    try {
      expr3();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 56:
          ;
          break;
        default:
          jj_la1[20] = jj_gen;
          break label_9;
        }
        jj_consume_token(56);
        expr3();
      }
    } finally {
      trace_return("expr4");
    }
  }

  final public void expr3() throws ParseException {
    trace_call("expr3");
    try {
      expr2();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 57:
        case 58:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_10;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 57:
          jj_consume_token(57);
          expr2();
          break;
        case 58:
          jj_consume_token(58);
          expr2();
          break;
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr3");
    }
  }

  final public void expr2() throws ParseException {
    trace_call("expr2");
    try {
      expr1();
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 59:
        case 60:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_11;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 59:
          jj_consume_token(59);
          expr1();
          break;
        case 60:
          jj_consume_token(60);
          expr1();
          break;
        default:
          jj_la1[24] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr2");
    }
  }

  final public void expr1() throws ParseException {
    trace_call("expr1");
    try {
      term();
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 61:
        case 62:
        case 63:
          ;
          break;
        default:
          jj_la1[25] = jj_gen;
          break label_12;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 61:
          jj_consume_token(61);
          term();
          break;
        case 62:
          jj_consume_token(62);
          term();
          break;
        case 63:
          jj_consume_token(63);
          term();
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr1");
    }
  }

  final public void term() throws ParseException {
    trace_call("term");
    try {
      if (jj_2_8(2147483647)) {
        jj_consume_token(32);
        type();
        jj_consume_token(24);
        term();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case INTEGER:
        case STRING:
        case 32:
        case 56:
        case 59:
        case 60:
        case 61:
        case 64:
        case 65:
        case 66:
        case 67:
          unary();
          break;
        default:
          jj_la1[27] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("term");
    }
  }

  final public void unary() throws ParseException {
    trace_call("unary");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 64:
        jj_consume_token(64);
        unary();
        break;
      case 65:
        jj_consume_token(65);
        unary();
        break;
      case 59:
        jj_consume_token(59);
        term();
        break;
      case 60:
        jj_consume_token(60);
        term();
        break;
      case 66:
        jj_consume_token(66);
        term();
        break;
      case 67:
        jj_consume_token(67);
        term();
        break;
      case 61:
        jj_consume_token(61);
        term();
        break;
      case 56:
        jj_consume_token(56);
        term();
        break;
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
        postfix();
        break;
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("unary");
    }
  }

  final public void postfix() throws ParseException {
    trace_call("postfix");
    try {
      primary();
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 29:
        case 32:
        case 64:
        case 65:
        case 68:
        case 69:
          ;
          break;
        default:
          jj_la1[29] = jj_gen;
          break label_13;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 64:
          jj_consume_token(64);
          break;
        case 65:
          jj_consume_token(65);
          break;
        case 29:
          jj_consume_token(29);
          expr();
          jj_consume_token(30);
          break;
        case 68:
          jj_consume_token(68);
          name();
          break;
        case 69:
          jj_consume_token(69);
          name();
          break;
        case 32:
          jj_consume_token(32);
          args();
          jj_consume_token(24);
          break;
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("postfix");
    }
  }

  final public void args() throws ParseException {
    trace_call("args");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
      case INTEGER:
      case STRING:
      case 32:
      case 56:
      case 59:
      case 60:
      case 61:
      case 64:
      case 65:
      case 66:
      case 67:
        expr();
        label_14:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 25:
            ;
            break;
          default:
            jj_la1[31] = jj_gen;
            break label_14;
          }
          jj_consume_token(25);
          expr();
        }
        break;
      default:
        jj_la1[32] = jj_gen;
        ;
      }
    } finally {
      trace_return("args");
    }
  }

  final public void primary() throws ParseException {
    trace_call("primary");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
        jj_consume_token(INTEGER);
        break;
      case STRING:
        jj_consume_token(STRING);
        break;
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        break;
      case 32:
        jj_consume_token(32);
        expr();
        jj_consume_token(24);
        break;
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("primary");
    }
  }

  final public List<DefinedVariable> defvars() throws ParseException {
    trace_call("defvars");
    try {
        List<DefinedVariable> defs = new ArrayList<DefinedVariable>();
        TypeNode type;
        String name;
        ExprNode init = null;
      type = type();
      name = name();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 33:
        jj_consume_token(33);
        init = expr();
        break;
      default:
        jj_la1[34] = jj_gen;
        ;
      }
                        defs.add(new DefinedVariable(type, name, init));
                        init = null;
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 25:
          ;
          break;
        default:
          jj_la1[35] = jj_gen;
          break label_15;
        }
        jj_consume_token(25);
        name = name();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 33:
          jj_consume_token(33);
          init = expr();
          break;
        default:
          jj_la1[36] = jj_gen;
          ;
        }
                        defs.add(new DefinedVariable(type, name, init));
                        init = null;
      }
      jj_consume_token(31);
                        {if (true) return defs;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defvars");
    }
  }

  final public DefinedFunction defun() throws ParseException {
    trace_call("defun");
    try {
        TypeRef ret;
        String n;
        Params ps;
        BlockNode body;
      ret = typeref();
      n = name();
      jj_consume_token(32);
      ps = params();
      jj_consume_token(24);
      body = block();
                        TypeRef t = new FunctionTypeRef(ret, ps.parametersTypeRef());
                        {if (true) return new DefinedFunction(new TypeNode(t), n, ps, body);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defun");
    }
  }

  final public List<DefinedVariable> defvar_list() throws ParseException {
    trace_call("defvar_list");
    try {
        List<DefinedVariable> result = new ArrayList<DefinedVariable>();
        List<DefinedVariable> vars;
      label_16:
      while (true) {
        if (jj_2_9(1)) {
          ;
        } else {
          break label_16;
        }
        vars = defvars();
                           result.addAll(vars);
      }
                        {if (true) return result;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defvar_list");
    }
  }

  final public Declarations top_defs() throws ParseException {
    trace_call("top_defs");
    try {
        Declarations decls = new Declarations();
        DefinedFunction defun;
        List<DefinedVariable> defvars;
        Constant defconst;
        StructNode defstruct;
        UnionNode defunion;
        TypedefNode typedef;
      label_17:
      while (true) {
        if (jj_2_10(1)) {
          ;
        } else {
          break label_17;
        }
        if (jj_2_11(2147483647)) {
          defun = defun();
                                decls.addDefun(defun);
        } else if (jj_2_12(3)) {
          defvars = defvars();
                                    decls.addDefvars(defvars);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
                        {if (true) return decls;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("top_defs");
    }
  }

  final public AST compilation_unit() throws ParseException {
    trace_call("compilation_unit");
    try {
        Token t;
        Declarations decls;
                t = getToken(1);
      decls = top_defs();
      jj_consume_token(0);
                        {if (true) return new AST(location(t), decls);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("compilation_unit");
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_3R_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(1)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    jj_lookingAhead = true;
    jj_semLA = isType(getToken(1).image);
    jj_lookingAhead = false;
    if (!jj_semLA || jj_scan_token(15)) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(29)) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(29)) return true;
    if (jj_scan_token(INTEGER)) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_22()) return true;
    if (jj_3R_31()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) jj_scanpos = xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(25)) return true;
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_scan_token(25)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_53()) return true;
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_54()) return true;
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(69)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_3R_53()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_60()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_scan_token(68)) return true;
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(29)) return true;
    if (jj_3R_53()) return true;
    if (jj_scan_token(30)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_46()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_47()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(56)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(61)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_22()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(67)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(66)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(65)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(64)) return true;
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_90() {
    if (jj_scan_token(61)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_87() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_90()) {
    jj_scanpos = xsp;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(32)) return true;
    if (jj_3R_22()) return true;
    if (jj_scan_token(24)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    return false;
  }

  private boolean jj_3R_88() {
    if (jj_scan_token(59)) return true;
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_84() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_88()) {
    jj_scanpos = xsp;
    if (jj_3R_89()) return true;
    }
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(63)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_scan_token(62)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_3R_20()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_87()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_85() {
    if (jj_scan_token(57)) return true;
    if (jj_3R_81()) return true;
    return false;
  }

  private boolean jj_3R_82() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_85()) {
    jj_scanpos = xsp;
    if (jj_3R_86()) return true;
    }
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_scan_token(60)) return true;
    if (jj_3R_83()) return true;
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_3R_83()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_84()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_scan_token(56)) return true;
    if (jj_3R_79()) return true;
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_scan_token(58)) return true;
    if (jj_3R_81()) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_scan_token(55)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_3R_81()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_82()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_scan_token(54)) return true;
    if (jj_3R_69()) return true;
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_3R_79()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_80()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_3R_77()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_78()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_68() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_71() {
    if (jj_scan_token(48)) return true;
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_3R_69()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_70()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(47)) return true;
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(53)) return true;
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_scan_token(51)) return true;
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_scan_token(50)) return true;
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(46)) return true;
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_scan_token(49)) return true;
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_3R_67()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_68()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_scan_token(44)) return true;
    if (jj_3R_53()) return true;
    if (jj_scan_token(45)) return true;
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_3R_65()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_66()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_63()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_64()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_3R_61()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_62()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_20()) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_20()) return true;
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(34)) {
    jj_scanpos = xsp;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(39)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_3R_59()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_3R_20()) return true;
    if (jj_3R_21()) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_3R_20()) return true;
    if (jj_scan_token(33)) return true;
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_3R_25()) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_3R_28()) return true;
    return false;
  }

  private boolean jj_3_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3_12()) return true;
    }
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(33)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  /** Whether we are looking ahead. */
  private boolean jj_lookingAhead = false;
  private boolean jj_semLA;
  private int jj_gen;
  final private int[] jj_la1 = new int[37];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x2000000,0x20000000,0x20000000,0x42,0x8881fd00,0x8881fd00,0x200,0x818000,0x818000,0x818000,0x1000,0x818000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x818000,0x818000,0x20000000,0x20000000,0x2000000,0x818000,0x818000,0x0,0x2000000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x39000001,0x39000001,0x0,0x39000001,0x39000001,0x39000001,0x0,0x39000001,0xffc,0x1000,0x4000,0x8000,0x3f0000,0x3f0000,0x400000,0x800000,0x1000000,0x6000000,0x6000000,0x18000000,0x18000000,0xe0000000,0xe0000000,0x39000001,0x39000001,0x1,0x1,0x0,0x39000001,0x1,0x2,0x0,0x2,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0xf,0xf,0x0,0xf,0xf,0xf,0x0,0xf,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xf,0xf,0x33,0x33,0x0,0xf,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[12];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 37; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = jj_lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[70];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 37; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 70; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private int trace_indent = 0;
  private boolean trace_enabled = true;

/** Enable tracing. */
  final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
    trace_enabled = false;
  }

  private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 12; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
